#!/bin/sh
numColumns=$1
errors=""

# if there are no arguments
if [ $# -eq 0 ]
then
    echo error: no arguments given. >&2
    exit 1
fi

# attempt to do arithmetic on the first argument
expr $1 + 1 2>/dev/null
# if exit status is not 0 or was negative, then it was not a valid column number
if [ $? != 0 ] || [ $1 -lt 0 ]
then
    echo error: first argument must be a positive integer. >&2
    exit 1
fi

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN>"
echo "<html>"
echo "  <head>"
echo "    <title>Pictures</title>"
echo "  </head>"
echo ""
echo "  <body>"
echo "    <h1>Pictures</h1>"
echo "    <table>"
echo "      <tr>"

# counter for current column number
column=0
# shift the arguments so that the number of column argument isn't used for a file
shift
# loop through all files in arguments
while test ${#} -gt 0
do
    # use the file function to get the file type
    fileType=`file -b $1 | cut -c1-4`

    #if file is type JPEG, then print the cell containing the picture
    if [ "$fileType" = "JPEG" ]
    then
echo "            <td><img src=\"$1\" height=100></td>"
    # increase the current column counter
    column=`expr $column + 1`
    else
        # if the file is not a JPEG, append error to error message to output
        errors="$errors$1 "
    fi

    # if the column counter is the same as the number of columns specified by the argument
    if [ $column -eq $numColumns ]
    then
    # reset the column counter back to 0
        column=0
echo "      </tr>"
echo "      <tr>"
    fi
    shift
done
echo "      </tr>"
echo "    </table>"
echo "  </body>"
echo "</html>"

# if there was an error with the files
if [ "$errors" != "" ]
then
    echo "$errors: not JPEG files." >&2
fi
